version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  postgres_performance:
    container_name: performance_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres_performance
    ports:
      - "5051:5432"
    restart: unless-stopped

  postgres_userservice:
    container_name: userservice_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/userservice
    ports:
      - "6051:5432"
    restart: unless-stopped

#  server:
#    build: ./workshiftservice
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/postgres
#
#volumes:
#  postgres_data:

#  discovery-server:
##    image: microservices-tutorial/discovery-server:latest
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - zipkin

  ## Keycloak Config with Mysql database
#  keycloak-mysql:
#    container_name: keycloak-mysql
#    image: mysql:5.7
#    volumes:
#      - ./mysql_keycloak_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: keycloak
#      MYSQL_USER: keycloak
#      MYSQL_PASSWORD: password
#
#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:18.0.0
#    command: ["start-dev", "--import-realm", "--features=scripts" ]
#    volumes:
##      - ./keycloak/custom-protocol-mapper.jar:/opt/keycloak/standalone/deployments/cust
#      - ./keycloak/custom-protocol-mapper.jar:/opt/keycloak/providers/custom-protocol-mapper.jar
#
#    environment:
#      DB_VENDOR: MYSQL
#      DB_ADDR: mysql
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: password
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_FEATURES: scripts,token-exchange
#      KEYCLOAK_FEATURES: scripts,token-exchange
#
#    ports:
#      - "8069:8080"
#    depends_on:
#      - keycloak-mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - mysql-data:/var/lib/mysql
  #    networks:
  #      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: ["start-dev", "--import-realm", "--features=scripts" ]
    volumes:
      - ./custom-protocol-mapper:/opt/keycloak/providers
      - ./keycloak/realms/:/opt/keycloak/data/import/

    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts,token-exchange
      KEYCLOAK_FEATURES: scripts,token-exchange
    ports:
      - 8069:8080
    depends_on:
      - mysql
  #    networks:
  #      - keycloak-network

volumes:
  mysql-data:
